### ISSUE TITLE
Taking Snapshot of Previous Day

### ISSUE THREAD

**Issue by Onalu** [elasticsearch/curator#244]
Hi,

I have daily indices like ``logstash-2015.01.06``. I am trying to take snapshot of the previous day with curator, but I cannot find a  good way. I can use something like ``--most-recent 1 --exclude-pattern 2015.01.06`` as a option which gives what I want, but providing pattern like this is not a good way. Using both ``--most-recent`` and  ``--older-than``  flags can be a good idea here if it is allowed. 

Is there any other way to do this?

**Comment by untergeek** [comment]
I addressed this at length in #174 with [this comment](https://github.com/elasticsearch/curator/issues/174#issuecomment-57056621).

Another issue is #190 

The bottom-line is that unless your indices change between snapshots, you will not be re-backing them up, because snapshots are at the segment level.

If you still require single-index snapshots, I suggest writing your own script that uses the [Elasticsearch Curator API](http://curator.readthedocs.org/).

**Comment by Onalu** [comment]
Even if the snapshots are segment level, there is still problem for me. 

On the  January 6th, ``logstash-2014.01.05`` and ``logstash-2014.01.06`` is backed up but ``logstash-2014.01.06`` is still incomplete. So, It will be re-backed up  on the January 7th. 

I want to take snapshot of the last complete index. I think I can use Curator API that you mentioned to do this. 

Thank you for your suggestion.

**Comment by untergeek** [comment]
But this is why with snapshots it's more common to snapshot `--older-than` and let them just stack up.  This way you're not "re-"snapshotting your older indices (they've been captured previously), and are only adding the most recent snapshots `--older-than` the time specified.

Best of luck.

**Comment by untergeek** [comment]
See if the changes in v3 help.  Closing for now.
