### ISSUE TITLE
Make `--all-indices` respect prefix

### ISSUE THREAD

**Issue by vincentbernat** [elasticsearch/curator#249]
Hi!

I would have expected `--all-indices` to respect `--prefix` instead of using `_all`. The use case is to use curator to also save non-time series data. For example:

```
curator snapshot --prefix "grafana-dash" --timestring "" --all-indices ...
```

**Comment by untergeek** [comment]
`--all-indices` is to enable Curator to snapshot _all_ indices, time-series or not.  This is by design.  If you are trying to snapshot a collection of non-timeseries indices, your current options are to snapshot everything via the `--all-indices` option, or to write your own script that uses the Curator API so you don't have to wrap your own REST calls in something else.
