### ISSUE TITLE
--prefix behaviour appears to be inconsistent.

### ISSUE THREAD

**Issue by quasipedia** [elasticsearch/curator#272]
I'm confused on how the `--prefix` option should work.  If I run `show --show-indices`, which according to the documentation should precisely serve [the purpose of verifying what indices are matched](https://github.com/elasticsearch/curator/wiki/Examples#show-indices-or-snapshots-matching-prefix) by `--prefix`, I get:

```
$ curator --host 10.0.101.15 show --show-indices
logstash-2015.01.26
logstash-2015.01.27
[...]
logstash-2015.02.23
logstash-2015.02.24
logstash-api-debug-2015.02.23
logstash-api-vanilla-2015.02.23
logstash-api-vanilla-2015.02.24
```

...however, when I run the `delete` command, it looks like the `logstash-api-xxx` indices are just ignored:

```
$ curator --host 10.0.101.15 delete --older-than 30
2015-02-24 16:03:50,145 INFO      Job starting...
2015-02-24 16:03:50,151 INFO      Deleting indices...
2015-02-24 16:03:50,177 INFO      logstash-2015.01.26 is within the threshold period (30 days).
2015-02-24 16:03:50,177 INFO      logstash-2015.01.27 is within the threshold period (30 days).
[....]
2015-02-24 16:03:50,181 INFO      logstash-2015.02.23 is within the threshold period (30 days).
2015-02-24 16:03:50,181 INFO      logstash-2015.02.24 is within the threshold period (30 days).
2015-02-24 16:03:50,181 INFO      Speficied indices deleted.
2015-02-24 16:03:50,181 INFO      Done in 0:00:00.052217.
```

**So, which command is telling the truth?**

**Comment by untergeek** [comment]
Unfortunately, they both are.  This is from a misunderstanding, which I am addressing in Curator 3.0, namely that I didn't necessarily want to prevent the showing of all indices by combining `prefix` _with_ a timestamp.

The `show` command only shows indices (or snapshots), but the formation of the arguments only adds `--prefix` and `--suffix`, and no `--time-unit` or `--timestring`.  (See: https://github.com/elasticsearch/curator/blob/master/curator/curator_script.py#L153-L163 and note the conspicuous absence of calls to `add_common_args(subparser)` where `--timestring` and `--time-unit` are referenced).

When `--time-unit` and `--timestring` are present, indices are obtained by regex, symbolically ^(prefix)(timestamp)(suffix)$.  Because the `show` command does not use a timestamp, it can only pull ^(prefix).*(suffix)$.

As a result, the current version of `show` will match a prefix of `logstash-` by default and show `logstash-.*` (since no suffix is provided), while `delete` _will_ have a `--timestring` and will not match `logstash-api-...`.

The Curator 3 branch I am working on will allow for arbitrary prefixes and timestamps and suffixes, such that a prefix of `log` will match anything beginning with log, regardless of the remainder of the index name--with or without a timestamp (it will act similarly with suffixes). It will match a timestamp (by timestring) anywhere in the index name, symbolically ^.*(timestamp).*$, and extract that value for comparison.  You will no longer be fixed to ^(prefix)(timestamp)(suffix)$ in the way that Curator has been up to this point.

**Comment by quasipedia** [comment]
@untergeek - Hey! Thank you for the informative explanation.  I will work around this in my crontab then.  It may be useful to add a note to the documentation of the current version though, as not to deceive doc-readers! :)

As a side note: I just wonder if you know about [docopt](http://docopt.org).  I started using it a few years back and I find my code greatly benefit from it in terms of readability (maybe you know about it and have good reasons not to use it, but I just wanted to give an heads-up in case you never stumbled on it)...

**Comment by untergeek** [comment]
This should be consistent now with the new beta.

**Comment by cfeio** [comment]
Is there any way to restrict to ^(prefix)(timestamp)(suffix)$ like it functioned in Curator v2? 

If I have index patterns of logstash-2015.05.08 and logstash-anotherindex-2015.05.08 I'd like to be able to specify to only delete "logstash-" and not "logstash-anotherindex".

**Comment by untergeek** [comment]
Hi @cfeio.  There are couple of ways to achieve this.

1. The [`--exclude`](http://www.elastic.co/guide/en/elasticsearch/client/curator/current/exclude.html) flag.  This would allow you to use an exclusion regex like `^.*anotherindex.*$` to exclude matching indices.
2. The [`--regex`](http://www.elastic.co/guide/en/elasticsearch/client/curator/current/regex.html) flag.  This would allow you to more fully define the index expression as `^logstash-\d{4}\d{2}\d{2}$`.  With this you would still need to use `--timestring` if you planned on doing time-based calculations.

**Comment by cfeio** [comment]
Thanks for the quick response! The regex flag accomplishes what I was looking for: <code>--regex '^logstash-(\d{4}.\d{2}.\d{2})'</code>
